version: '3.7'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/entrypoint.sh']
    volumes:
      - backend-data:/usr/src/app
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=production
    networks:
      - api_bridge
    restart: always

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    networks:
      - api_bridge
    ports:
      - "8800:80"
      - "4433:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    networks:
      - api_bridge
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

##### Networks #####
networks:
  api_bridge:
    driver: bridge

##### Volumes #####
volumes:
  backend-data: