version: '3.7'

##### Services #####
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    #depends_on:
    #  - cache
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=production
    networks:
      - api_bridge
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5002:80
    networks:
      - api_bridge
    restart: always

#  cache:
#    image: redis:6.2-alpine
#    restart: always
#    networks:
#      - api_bridge
#    ports:
#      - '6379:6379'
#    command: redis-server --save 20 1 --loglevel warning
#    volumes: 
#      - cache:/data

##### Networks #####
networks:
  api_bridge:
    driver: bridge

##### Volumes #####
#volumes:
#  cache:
#    driver: local