version: '3.7'

services:

  phosys-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/entrypoint.sh']
    volumes:
      - phosys-backend-data:/usr/src/app
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
    networks:
      - api_bridge
    restart: always

  phosys-nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4433:443
    depends_on:
      - phosys-backend
    networks:
      - api_bridge
      
##### Networks #####
networks:
  api_bridge:
    driver: bridge

##### Volumes #####
volumes:
  phosys-backend-data: