version: '3.7'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/entrypoint.sh']
    volumes:
      - backend-data:/usr/src/app
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=production
    networks:
      - api_bridge
    restart: always

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4433:443
    depends_on:
      - backend
    networks:
      - api_bridge

##### Networks #####
networks:
  api_bridge:
    driver: bridge

##### Volumes #####
volumes:
  backend-data: