on: [push]

jobs:
  docker-test:
    runs-on: ubuntu-latest
    name: Build and run Docker image
    steps:
        
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Build Docker image
        run: docker compose build --no-cache
        
      - name: Run Docker compose
        run:  docker compose up -d --force-recreate