name: all-lints

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: weibullguy/python-lint-plus@master
        with:
          python-root-list: "backend"
          use-check-manifest: false
          use-pyroma: false
          extra-rstcheck-options: "-r"
          docformatter-version: "==1.5.0"