on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          component: true
          working-directory: frontend
    
  docker-test:
    runs-on: ubuntu-latest
    name: Build and run Docker image
    steps:
        
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Build Docker image
        run: docker compose build --no-cache
        
      - name: Run Docker compose
        run:  docker compose up -d --force-recreate
      
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: weibullguy/python-lint-plus@master
        with:
          python-root-list: "backend"
          use-check-manifest: false
          use-pyroma: false
          extra-rstcheck-options: "-r"
          docformatter-version: "==1.5.0"